// This file will be auto-generated by: npm run session-stash:gen-types
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > apps/session-stash/src/app/models/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      session_stash_drills: {
        Row: {
          id: string;
          user_id: string;
          url: string;
          title: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          url: string;
          title: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          url?: string;
          title?: string;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      session_stash_system_tags: {
        Row: {
          id: string;
          name: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          name?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      session_stash_user_tags: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      session_stash_drill_system_tags: {
        Row: {
          drill_id: string;
          system_tag_id: string;
        };
        Insert: {
          drill_id: string;
          system_tag_id: string;
        };
        Update: {
          drill_id?: string;
          system_tag_id?: string;
        };
        Relationships: [];
      };
      session_stash_drill_user_tags: {
        Row: {
          drill_id: string;
          user_tag_id: string;
        };
        Insert: {
          drill_id: string;
          user_tag_id: string;
        };
        Update: {
          drill_id?: string;
          user_tag_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
