// This file will be auto-generated by: npm run gen:types
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > apps/session-stash/src/app/models/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      drills: {
        Row: {
          id: string;
          user_id: string;
          url: string;
          title: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          url: string;
          title: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          url?: string;
          title?: string;
          notes?: string | null;
          created_at?: string;
        };
      };
      system_tags: {
        Row: {
          id: string;
          name: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          name?: string;
          sort_order?: number;
        };
      };
      user_tags: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          created_at?: string;
        };
      };
      drill_system_tags: {
        Row: {
          drill_id: string;
          system_tag_id: string;
        };
        Insert: {
          drill_id: string;
          system_tag_id: string;
        };
        Update: {
          drill_id?: string;
          system_tag_id?: string;
        };
      };
      drill_user_tags: {
        Row: {
          drill_id: string;
          user_tag_id: string;
        };
        Insert: {
          drill_id: string;
          user_tag_id: string;
        };
        Update: {
          drill_id?: string;
          user_tag_id?: string;
        };
      };
    };
  };
}
