/**
 * Build-time environment injection script
 *
 * Reads from .env.local and generates environment.ts for Angular
 *
 * Usage:
 *   node scripts/set-env.js
 *
 * Or add to package.json:
 *   "scripts": { "set-env": "node scripts/set-env.js" }
 */

const fs = require('fs');
const path = require('path');

// Try to load dotenv if available
try {
  require('dotenv').config({ path: '.env.local' });
} catch {
  console.log('ℹ️  dotenv not installed, using process.env directly');
}

const targetPath = path.join(
  __dirname,
  '../apps/session-stash/src/environments/environment.ts'
);

// Validate required environment variables
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missing = required.filter((key) => !process.env[key]);

if (missing.length > 0) {
  console.error('❌ Missing required environment variables:');
  missing.forEach((key) => console.error(`   - ${key}`));
  console.error('\nCreate a .env.local file with these variables or set them in your environment.');
  console.error('See .env.example for reference.\n');
  process.exit(1);
}

const isProduction = process.env.PRODUCTION === 'true';
const version = process.env.npm_package_version || '0.0.1';

const envConfigFile = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: ${isProduction},
  supabase: {
    url: '${process.env.SUPABASE_URL}',
    anonKey: '${process.env.SUPABASE_ANON_KEY}',
  },
  app: {
    name: 'Session Stash',
    version: '${version}',
  },
};
`;

fs.writeFileSync(targetPath, envConfigFile);

console.log(`✅ Environment file generated at ${targetPath}`);
console.log(`   - Production: ${isProduction}`);
console.log(`   - Supabase URL: ${process.env.SUPABASE_URL?.substring(0, 30)}...`);
console.log(`   - Version: ${version}`);
